# Import FastAPI core class
from fastapi import FastAPI
# Import explicit JSON response class to guarantee Content‑Type
from fastapi.responses import JSONResponse

# Initialise the FastAPI application with a title and version.
# These values appear in the autogenerated OpenAPI docs.
app = FastAPI(title="Heartbeat Service", version="0.1.0")

# Define a GET endpoint at /heartbeat.
# `response_class=JSONResponse` forces JSON output.
# `tags=["Health"]` groups this endpoint in the docs under “Health”.
@app.get("/heartbeat", response_class=JSONResponse, tags=["Health"])
async def heartbeat() -> dict:
    """
    Liveness/health‑check endpoint.
    Returns a simple JSON payload confirming the service is alive.
    """
    # Static payload – can be expanded later to include deeper diagnostics.
    return {"status": "ok", "message": "Service is up and running"}
